language: go
sudo: false
go:
  - tip

services:
  - postgresql

before_install:
  - go get github.com/mattn/goveralls

before_script:
  - psql -c 'create database spells;' -U postgres
  - psql -d spells -U postgres -f db/create_spells_table.sql

script:
 - $GOPATH/bin/goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN
