DROP TABLE IF EXISTS classes;

CREATE TABLE classes (
name VARCHAR NOT NULL,
class VARCHAR NOT NULL
);


INSERT INTO classes (name, class) VALUES ('True Strike', 'Bard');
INSERT INTO classes (name, class) VALUES ('True Strike', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('True Strike', 'Warlock');
INSERT INTO classes (name, class) VALUES ('True Strike', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Insect Plague', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Insect Plague', 'Druid');
INSERT INTO classes (name, class) VALUES ('Insect Plague', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Giant Insect', 'Druid');
INSERT INTO classes (name, class) VALUES ('Skywrite (Ritual)', 'Bard');
INSERT INTO classes (name, class) VALUES ('Skywrite (Ritual)', 'Druid');
INSERT INTO classes (name, class) VALUES ('Skywrite (Ritual)', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Booming Blade', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Booming Blade', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Booming Blade', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Conjure Elemental', 'Druid');
INSERT INTO classes (name, class) VALUES ('Conjure Elemental', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Guardian of Faith', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Create Food and Water', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Create Food and Water', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Vicious Mockery', 'Bard');
INSERT INTO classes (name, class) VALUES ('Remove Curse', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Remove Curse', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Remove Curse', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Remove Curse', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Resurrection', 'Bard');
INSERT INTO classes (name, class) VALUES ('Resurrection', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Antilife Shell', 'Druid');
INSERT INTO classes (name, class) VALUES ('Vampiric Touch', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Vampiric Touch', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Tsunami', 'Druid');
INSERT INTO classes (name, class) VALUES ('Pass Without Trace', 'Druid');
INSERT INTO classes (name, class) VALUES ('Pass Without Trace', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Antipathy/Sympathy', 'Druid');
INSERT INTO classes (name, class) VALUES ('Antipathy/Sympathy', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Banishment', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Banishment', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Banishment', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Banishment', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Banishment', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Water Breathing (Ritual)', 'Druid');
INSERT INTO classes (name, class) VALUES ('Water Breathing (Ritual)', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Water Breathing (Ritual)', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Water Breathing (Ritual)', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Forcecage', 'Bard');
INSERT INTO classes (name, class) VALUES ('Forcecage', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Forcecage', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Mirror Image', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Mirror Image', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Mirror Image', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Time Stop', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Time Stop', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Speak with Animals (Ritual)', 'Bard');
INSERT INTO classes (name, class) VALUES ('Speak with Animals (Ritual)', 'Druid');
INSERT INTO classes (name, class) VALUES ('Speak with Animals (Ritual)', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Power Word Kill', 'Bard');
INSERT INTO classes (name, class) VALUES ('Power Word Kill', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Power Word Kill', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Power Word Kill', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Sword Burst', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Sword Burst', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Sword Burst', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Dispel Evil and Good', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Dispel Evil and Good', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Commune (Ritual)', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Flame Blade', 'Druid');
INSERT INTO classes (name, class) VALUES ('Death Ward', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Death Ward', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Invisibility', 'Bard');
INSERT INTO classes (name, class) VALUES ('Invisibility', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Invisibility', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Invisibility', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Tasha’s Hideous Laughter', 'Bard');
INSERT INTO classes (name, class) VALUES ('Tasha’s Hideous Laughter', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Maze', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Color Spray', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Color Spray', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Lightning Lure', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Lightning Lure', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Lightning Lure', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Poison Spray', 'Druid');
INSERT INTO classes (name, class) VALUES ('Poison Spray', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Poison Spray', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Poison Spray', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Arcane Lock', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Heal', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Heal', 'Druid');
INSERT INTO classes (name, class) VALUES ('Meld into Stone (Ritual)', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Meld into Stone (Ritual)', 'Druid');
INSERT INTO classes (name, class) VALUES ('Magic Stone', 'Druid');
INSERT INTO classes (name, class) VALUES ('Magic Stone', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Mordenkainen’s Sword', 'Bard');
INSERT INTO classes (name, class) VALUES ('Mordenkainen’s Sword', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Entangle', 'Druid');
INSERT INTO classes (name, class) VALUES ('Prismatic Wall', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Light', 'Bard');
INSERT INTO classes (name, class) VALUES ('Light', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Light', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Light', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Otto’s Irresistible Dance', 'Bard');
INSERT INTO classes (name, class) VALUES ('Otto’s Irresistible Dance', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Elemental Weapon', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Zone of Truth', 'Bard');
INSERT INTO classes (name, class) VALUES ('Zone of Truth', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Zone of Truth', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Mage Hand', 'Bard');
INSERT INTO classes (name, class) VALUES ('Mage Hand', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Mage Hand', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Mage Hand', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Counterspell', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Counterspell', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Counterspell', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Finger of Death', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Finger of Death', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Finger of Death', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Imprisonment', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Imprisonment', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Daylight', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Daylight', 'Druid');
INSERT INTO classes (name, class) VALUES ('Daylight', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Daylight', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Daylight', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Feather Fall', 'Bard');
INSERT INTO classes (name, class) VALUES ('Feather Fall', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Feather Fall', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Wall of Force', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Darkness', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Darkness', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Darkness', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Druidcraft', 'Druid');
INSERT INTO classes (name, class) VALUES ('Compulsion', 'Bard');
INSERT INTO classes (name, class) VALUES ('Blindness/Deafness', 'Bard');
INSERT INTO classes (name, class) VALUES ('Blindness/Deafness', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Blindness/Deafness', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Blindness/Deafness', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Beast Bond', 'Druid');
INSERT INTO classes (name, class) VALUES ('Beast Bond', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Dust Devil', 'Druid');
INSERT INTO classes (name, class) VALUES ('Dust Devil', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Dust Devil', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Ice Knife', 'Druid');
INSERT INTO classes (name, class) VALUES ('Ice Knife', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Ice Knife', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Ray of Sickness', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Ray of Sickness', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Greater Restoration', 'Bard');
INSERT INTO classes (name, class) VALUES ('Greater Restoration', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Greater Restoration', 'Druid');
INSERT INTO classes (name, class) VALUES ('Mordenkainen’s Private Sanctum', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Major Image', 'Bard');
INSERT INTO classes (name, class) VALUES ('Major Image', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Major Image', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Major Image', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Bless', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Bless', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Astral Projection', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Astral Projection', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Astral Projection', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Conjure Minor Elementals', 'Druid');
INSERT INTO classes (name, class) VALUES ('Conjure Minor Elementals', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Enhance Ability', 'Bard');
INSERT INTO classes (name, class) VALUES ('Enhance Ability', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Enhance Ability', 'Druid');
INSERT INTO classes (name, class) VALUES ('Enhance Ability', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Contact Other Plane (Ritual)', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Contact Other Plane (Ritual)', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Whirlwind', 'Druid');
INSERT INTO classes (name, class) VALUES ('Whirlwind', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Tongues', 'Bard');
INSERT INTO classes (name, class) VALUES ('Tongues', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Tongues', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Tongues', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Tongues', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Healing Word', 'Bard');
INSERT INTO classes (name, class) VALUES ('Healing Word', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Healing Word', 'Druid');
INSERT INTO classes (name, class) VALUES ('Legend Lore', 'Bard');
INSERT INTO classes (name, class) VALUES ('Legend Lore', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Legend Lore', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Arcane Eye', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Spider Climb', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Spider Climb', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Spider Climb', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Vitriolic Sphere', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Vitriolic Sphere', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Ray of Frost', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Ray of Frost', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Polymorph', 'Bard');
INSERT INTO classes (name, class) VALUES ('Polymorph', 'Druid');
INSERT INTO classes (name, class) VALUES ('Polymorph', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Polymorph', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Power Word Stun', 'Bard');
INSERT INTO classes (name, class) VALUES ('Power Word Stun', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Power Word Stun', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Power Word Stun', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Hallucinatory Terrain', 'Bard');
INSERT INTO classes (name, class) VALUES ('Hallucinatory Terrain', 'Druid');
INSERT INTO classes (name, class) VALUES ('Hallucinatory Terrain', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Hallucinatory Terrain', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Green-Flame Blade', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Green-Flame Blade', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Green-Flame Blade', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Call Lightning', 'Druid');
INSERT INTO classes (name, class) VALUES ('Aura of Life', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Blinding Smite', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Detect Poison and Disease', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Detect Poison and Disease', 'Druid');
INSERT INTO classes (name, class) VALUES ('Detect Poison and Disease', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Detect Poison and Disease', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Dissonant Whispers', 'Bard');
INSERT INTO classes (name, class) VALUES ('Faerie Fire', 'Bard');
INSERT INTO classes (name, class) VALUES ('Faerie Fire', 'Druid');
INSERT INTO classes (name, class) VALUES ('True Seeing', 'Bard');
INSERT INTO classes (name, class) VALUES ('True Seeing', 'Cleric');
INSERT INTO classes (name, class) VALUES ('True Seeing', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('True Seeing', 'Warlock');
INSERT INTO classes (name, class) VALUES ('True Seeing', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Dominate Person', 'Bard');
INSERT INTO classes (name, class) VALUES ('Dominate Person', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Dominate Person', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Flame Strike', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Magic Mouth (Ritual)', 'Bard');
INSERT INTO classes (name, class) VALUES ('Magic Mouth (Ritual)', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Friends', 'Bard');
INSERT INTO classes (name, class) VALUES ('Friends', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Friends', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Friends', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Move Earth', 'Druid');
INSERT INTO classes (name, class) VALUES ('Move Earth', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Move Earth', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Storm of Vengence', 'Druid');
INSERT INTO classes (name, class) VALUES ('Detect Evil and Good', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Detect Evil and Good', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Seeming', 'Bard');
INSERT INTO classes (name, class) VALUES ('Seeming', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Seeming', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Mind Blank', 'Bard');
INSERT INTO classes (name, class) VALUES ('Mind Blank', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Stoneskin', 'Druid');
INSERT INTO classes (name, class) VALUES ('Stoneskin', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Stoneskin', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Stoneskin', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Speak with Plants', 'Bard');
INSERT INTO classes (name, class) VALUES ('Speak with Plants', 'Druid');
INSERT INTO classes (name, class) VALUES ('Speak with Plants', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Protection from Evil and Good', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Protection from Evil and Good', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Protection from Evil and Good', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Protection from Evil and Good', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Aganazzar’s Scorcher', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Aganazzar’s Scorcher', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Augury (Ritual)', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Blur', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Blur', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Blight', 'Druid');
INSERT INTO classes (name, class) VALUES ('Blight', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Blight', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Blight', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Shapechange', 'Druid');
INSERT INTO classes (name, class) VALUES ('Shapechange', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Armor of Agathys', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Charm Person', 'Bard');
INSERT INTO classes (name, class) VALUES ('Charm Person', 'Druid');
INSERT INTO classes (name, class) VALUES ('Charm Person', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Charm Person', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Charm Person', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Find Steed', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Water Walk (Ritual)', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Water Walk (Ritual)', 'Druid');
INSERT INTO classes (name, class) VALUES ('Water Walk (Ritual)', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Water Walk (Ritual)', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Branding Smite', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Goodberry', 'Druid');
INSERT INTO classes (name, class) VALUES ('Goodberry', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Crown of Madness', 'Bard');
INSERT INTO classes (name, class) VALUES ('Crown of Madness', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Crown of Madness', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Crown of Madness', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Knock', 'Bard');
INSERT INTO classes (name, class) VALUES ('Knock', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Knock', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Searing Smite', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Divine Word', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Investiture of Ice', 'Druid');
INSERT INTO classes (name, class) VALUES ('Investiture of Ice', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Investiture of Ice', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Investiture of Ice', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Fireball', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Fireball', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Shield', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Shield', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Nondetection', 'Bard');
INSERT INTO classes (name, class) VALUES ('Nondetection', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Nondetection', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Resistance', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Resistance', 'Druid');
INSERT INTO classes (name, class) VALUES ('Mordenkainen’s Magnificent Mansion', 'Bard');
INSERT INTO classes (name, class) VALUES ('Mordenkainen’s Magnificent Mansion', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Locate Animals or Plants (Ritual)', 'Bard');
INSERT INTO classes (name, class) VALUES ('Locate Animals or Plants (Ritual)', 'Druid');
INSERT INTO classes (name, class) VALUES ('Locate Animals or Plants (Ritual)', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Circle of Power', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Blade Ward', 'Bard');
INSERT INTO classes (name, class) VALUES ('Blade Ward', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Blade Ward', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Blade Ward', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Hallow', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Lightning Arrow', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Conjure Volley', 'Ranger');
INSERT INTO classes (name, class) VALUES ('False Life', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('False Life', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Snilloc’s Snowball Swarm', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Snilloc’s Snowball Swarm', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Word of Recall', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Gust of Wind', 'Druid');
INSERT INTO classes (name, class) VALUES ('Gust of Wind', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Gust of Wind', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Calm Emotions', 'Bard');
INSERT INTO classes (name, class) VALUES ('Calm Emotions', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Cone of Cold', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Cone of Cold', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Spiritual Weapon', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Create or Destroy Water', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Create or Destroy Water', 'Druid');
INSERT INTO classes (name, class) VALUES ('Wall of Water', 'Druid');
INSERT INTO classes (name, class) VALUES ('Wall of Water', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Wall of Water', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Divine Favor', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Awaken', 'Bard');
INSERT INTO classes (name, class) VALUES ('Awaken', 'Druid');
INSERT INTO classes (name, class) VALUES ('Spike Growth', 'Druid');
INSERT INTO classes (name, class) VALUES ('Spike Growth', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Hail of Thorns', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Contagion', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Contagion', 'Druid');
INSERT INTO classes (name, class) VALUES ('Mold earth', 'Druid');
INSERT INTO classes (name, class) VALUES ('Mold earth', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Mold earth', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Hellish Rebuke', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Scorching Ray', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Scorching Ray', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Conjure Celestial', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Reincarnate', 'Druid');
INSERT INTO classes (name, class) VALUES ('Enlarge/Reduce', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Enlarge/Reduce', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Contingency', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Planar Ally', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Maelstrom', 'Druid');
INSERT INTO classes (name, class) VALUES ('Melf’s Minute Meteors', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Melf’s Minute Meteors', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Blink', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Blink', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Jump', 'Druid');
INSERT INTO classes (name, class) VALUES ('Jump', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Jump', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Jump', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Symbol', 'Bard');
INSERT INTO classes (name, class) VALUES ('Symbol', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Symbol', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Pyrotechnics', 'Bard');
INSERT INTO classes (name, class) VALUES ('Pyrotechnics', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Pyrotechnics', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Banishing Smite', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Longstrider', 'Bard');
INSERT INTO classes (name, class) VALUES ('Longstrider', 'Druid');
INSERT INTO classes (name, class) VALUES ('Longstrider', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Longstrider', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Wall of Stone', 'Druid');
INSERT INTO classes (name, class) VALUES ('Wall of Stone', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Wall of Stone', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Sacred Flame', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Elemental Bane', 'Druid');
INSERT INTO classes (name, class) VALUES ('Elemental Bane', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Elemental Bane', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Spare the Dying', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Find Familiar (Ritual)', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Dimension Door', 'Bard');
INSERT INTO classes (name, class) VALUES ('Dimension Door', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Dimension Door', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Dimension Door', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Control Weather', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Control Weather', 'Druid');
INSERT INTO classes (name, class) VALUES ('Control Weather', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Telekinesis', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Telekinesis', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Plant Growth', 'Bard');
INSERT INTO classes (name, class) VALUES ('Plant Growth', 'Druid');
INSERT INTO classes (name, class) VALUES ('Plant Growth', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Guidance', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Guidance', 'Druid');
INSERT INTO classes (name, class) VALUES ('Aura of Vitality', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Modify Memory', 'Bard');
INSERT INTO classes (name, class) VALUES ('Modify Memory', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Barkskin', 'Druid');
INSERT INTO classes (name, class) VALUES ('Barkskin', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Unseen Servant (Ritual)', 'Bard');
INSERT INTO classes (name, class) VALUES ('Unseen Servant (Ritual)', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Unseen Servant (Ritual)', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Purify Food and Drink (Ritual)', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Purify Food and Drink (Ritual)', 'Druid');
INSERT INTO classes (name, class) VALUES ('Purify Food and Drink (Ritual)', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Bane', 'Bard');
INSERT INTO classes (name, class) VALUES ('Bane', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Watery Sphere', 'Druid');
INSERT INTO classes (name, class) VALUES ('Watery Sphere', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Watery Sphere', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Otiluke’s Freezing Sphere', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Transport via Plants', 'Druid');
INSERT INTO classes (name, class) VALUES ('Transmute Rock', 'Druid');
INSERT INTO classes (name, class) VALUES ('Transmute Rock', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Detect Magic (Ritual)', 'Bard');
INSERT INTO classes (name, class) VALUES ('Detect Magic (Ritual)', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Detect Magic (Ritual)', 'Druid');
INSERT INTO classes (name, class) VALUES ('Detect Magic (Ritual)', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Detect Magic (Ritual)', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Detect Magic (Ritual)', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Detect Magic (Ritual)', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Beast Sense (Ritual)', 'Druid');
INSERT INTO classes (name, class) VALUES ('Beast Sense (Ritual)', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Darkvision', 'Druid');
INSERT INTO classes (name, class) VALUES ('Darkvision', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Darkvision', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Darkvision', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Mass Heal', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Heroes’ Feast', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Heroes’ Feast', 'Druid');
INSERT INTO classes (name, class) VALUES ('Passwall', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Fire Shield', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Circle of Death', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Circle of Death', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Circle of Death', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Confusion', 'Bard');
INSERT INTO classes (name, class) VALUES ('Confusion', 'Druid');
INSERT INTO classes (name, class) VALUES ('Confusion', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Confusion', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Clone', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Scrying', 'Bard');
INSERT INTO classes (name, class) VALUES ('Scrying', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Scrying', 'Druid');
INSERT INTO classes (name, class) VALUES ('Scrying', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Scrying', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Thunderous Smite', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Thorn Whip', 'Druid');
INSERT INTO classes (name, class) VALUES ('Protection from Poison', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Protection from Poison', 'Druid');
INSERT INTO classes (name, class) VALUES ('Protection from Poison', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Protection from Poison', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Fog Cloud', 'Druid');
INSERT INTO classes (name, class) VALUES ('Fog Cloud', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Fog Cloud', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Fog Cloud', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Wish', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Wish', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Wall of Fire', 'Druid');
INSERT INTO classes (name, class) VALUES ('Wall of Fire', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Wall of Fire', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Aura of Purity', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Divination (Ritual)', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Sanctuary', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Creation', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Creation', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Prestidigitation', 'Bard');
INSERT INTO classes (name, class) VALUES ('Prestidigitation', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Prestidigitation', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Prestidigitation', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Detect Thoughts', 'Bard');
INSERT INTO classes (name, class) VALUES ('Detect Thoughts', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Detect Thoughts', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Frostbite', 'Druid');
INSERT INTO classes (name, class) VALUES ('Frostbite', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Frostbite', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Frostbite', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Simulacrum', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Web', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Web', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Teleport', 'Bard');
INSERT INTO classes (name, class) VALUES ('Teleport', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Teleport', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Heroism', 'Bard');
INSERT INTO classes (name, class) VALUES ('Heroism', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Conjure Animals', 'Druid');
INSERT INTO classes (name, class) VALUES ('Conjure Animals', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Acid Splash', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Acid Splash', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Gate', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Gate', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Gate', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Shillelagh', 'Druid');
INSERT INTO classes (name, class) VALUES ('Commune with Nature (Ritual)', 'Druid');
INSERT INTO classes (name, class) VALUES ('Commune with Nature (Ritual)', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Staggering Smite', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Earthquake', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Earthquake', 'Druid');
INSERT INTO classes (name, class) VALUES ('Earthquake', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Glyph of Warding', 'Bard');
INSERT INTO classes (name, class) VALUES ('Glyph of Warding', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Glyph of Warding', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Lightning Bolt', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Lightning Bolt', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Guiding Bolt', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Greater Invisibility', 'Bard');
INSERT INTO classes (name, class) VALUES ('Greater Invisibility', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Greater Invisibility', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Flaming Sphere', 'Druid');
INSERT INTO classes (name, class) VALUES ('Flaming Sphere', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Arms of Hadar', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Drawmij’s Instant Summon (Ritual)', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Find Traps', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Find Traps', 'Druid');
INSERT INTO classes (name, class) VALUES ('Find Traps', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Regenerate', 'Bard');
INSERT INTO classes (name, class) VALUES ('Regenerate', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Regenerate', 'Druid');
INSERT INTO classes (name, class) VALUES ('Chain Lightning', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Chain Lightning', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Hunger of Hadar', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Conjure Fey', 'Druid');
INSERT INTO classes (name, class) VALUES ('Conjure Fey', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Project Image', 'Bard');
INSERT INTO classes (name, class) VALUES ('Project Image', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Identify (Ritual)', 'Bard');
INSERT INTO classes (name, class) VALUES ('Identify (Ritual)', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Arcane Gate', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Arcane Gate', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Arcane Gate', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Misty Step', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Misty Step', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Misty Step', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Mass Cure Wounds', 'Bard');
INSERT INTO classes (name, class) VALUES ('Mass Cure Wounds', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Mass Cure Wounds', 'Druid');
INSERT INTO classes (name, class) VALUES ('Comprehend Languages (Ritual)', 'Bard');
INSERT INTO classes (name, class) VALUES ('Comprehend Languages (Ritual)', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Comprehend Languages (Ritual)', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Comprehend Languages (Ritual)', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Catapult', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Catapult', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Control Winds', 'Druid');
INSERT INTO classes (name, class) VALUES ('Control Winds', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Control Winds', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Warding Bond', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Cure Wounds', 'Bard');
INSERT INTO classes (name, class) VALUES ('Cure Wounds', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Cure Wounds', 'Druid');
INSERT INTO classes (name, class) VALUES ('Cure Wounds', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Cure Wounds', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Fire Bolt', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Fire Bolt', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Investiture of Wind', 'Druid');
INSERT INTO classes (name, class) VALUES ('Investiture of Wind', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Investiture of Wind', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Investiture of Wind', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Warding Wind', 'Bard');
INSERT INTO classes (name, class) VALUES ('Warding Wind', 'Druid');
INSERT INTO classes (name, class) VALUES ('Warding Wind', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Sending', 'Bard');
INSERT INTO classes (name, class) VALUES ('Sending', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Sending', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Forbiddance (Ritual)', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Hold Monster', 'Bard');
INSERT INTO classes (name, class) VALUES ('Hold Monster', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Hold Monster', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Hold Monster', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Witch Bolt', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Witch Bolt', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Witch Bolt', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Protection from Energy', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Protection from Energy', 'Druid');
INSERT INTO classes (name, class) VALUES ('Protection from Energy', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Protection from Energy', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Protection from Energy', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Programmed Illusion', 'Bard');
INSERT INTO classes (name, class) VALUES ('Programmed Illusion', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Plane Shift', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Plane Shift', 'Druid');
INSERT INTO classes (name, class) VALUES ('Plane Shift', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Plane Shift', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Plane Shift', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Weird', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Harm', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Magic Jar', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Expeditious Retreat', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Expeditious Retreat', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Expeditious Retreat', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Investiture of Flame', 'Druid');
INSERT INTO classes (name, class) VALUES ('Investiture of Flame', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Investiture of Flame', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Investiture of Flame', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Disguise Self', 'Bard');
INSERT INTO classes (name, class) VALUES ('Disguise Self', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Disguise Self', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Wall of Ice', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Bestow Curse', 'Bard');
INSERT INTO classes (name, class) VALUES ('Bestow Curse', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Bestow Curse', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Gentle Repose (Ritual)', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Gentle Repose (Ritual)', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Thaumaturgy', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Magic Weapon', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Magic Weapon', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Hex', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Foresight', 'Bard');
INSERT INTO classes (name, class) VALUES ('Foresight', 'Druid');
INSERT INTO classes (name, class) VALUES ('Foresight', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Foresight', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Phantasmal Killer', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Melf’s Acid Arrow', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Wrathful Smite', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Shape Water', 'Druid');
INSERT INTO classes (name, class) VALUES ('Shape Water', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Shape Water', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Earth Tremor', 'Bard');
INSERT INTO classes (name, class) VALUES ('Earth Tremor', 'Druid');
INSERT INTO classes (name, class) VALUES ('Earth Tremor', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Earth Tremor', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Produce Flame', 'Druid');
INSERT INTO classes (name, class) VALUES ('Sunbeam', 'Druid');
INSERT INTO classes (name, class) VALUES ('Sunbeam', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Sunbeam', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Create Bonfire', 'Druid');
INSERT INTO classes (name, class) VALUES ('Create Bonfire', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Create Bonfire', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Create Bonfire', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Shatter', 'Bard');
INSERT INTO classes (name, class) VALUES ('Shatter', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Shatter', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Shatter', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Fire Storm', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Fire Storm', 'Druid');
INSERT INTO classes (name, class) VALUES ('Fire Storm', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Gaseous Form', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Gaseous Form', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Gaseous Form', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Planar Binding', 'Bard');
INSERT INTO classes (name, class) VALUES ('Planar Binding', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Planar Binding', 'Druid');
INSERT INTO classes (name, class) VALUES ('Planar Binding', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Dispel Magic', 'Bard');
INSERT INTO classes (name, class) VALUES ('Dispel Magic', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Dispel Magic', 'Druid');
INSERT INTO classes (name, class) VALUES ('Dispel Magic', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Dispel Magic', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Dispel Magic', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Dispel Magic', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Disintegrate', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Disintegrate', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Primordial Ward', 'Druid');
INSERT INTO classes (name, class) VALUES ('Storm Sphere', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Storm Sphere', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Incendiary Cloud', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Incendiary Cloud', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Maximilian’s Earthen Grasp', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Maximilian’s Earthen Grasp', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Stinking Cloud', 'Bard');
INSERT INTO classes (name, class) VALUES ('Stinking Cloud', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Stinking Cloud', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Flesh to Stone', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Flesh to Stone', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Minor Illusion', 'Bard');
INSERT INTO classes (name, class) VALUES ('Minor Illusion', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Minor Illusion', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Minor Illusion', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Etherealness', 'Bard');
INSERT INTO classes (name, class) VALUES ('Etherealness', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Etherealness', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Etherealness', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Etherealness', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Control Flames', 'Druid');
INSERT INTO classes (name, class) VALUES ('Control Flames', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Control Flames', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Sleet Storm', 'Druid');
INSERT INTO classes (name, class) VALUES ('Sleet Storm', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Sleet Storm', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Demiplane', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Demiplane', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Slow', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Slow', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Wind Walk', 'Druid');
INSERT INTO classes (name, class) VALUES ('Wind Wall', 'Druid');
INSERT INTO classes (name, class) VALUES ('Wind Wall', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Tenser’s Floating Disk (Ritual)', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Freedom of Movement', 'Bard');
INSERT INTO classes (name, class) VALUES ('Freedom of Movement', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Freedom of Movement', 'Druid');
INSERT INTO classes (name, class) VALUES ('Freedom of Movement', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Mending', 'Bard');
INSERT INTO classes (name, class) VALUES ('Mending', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Mending', 'Druid');
INSERT INTO classes (name, class) VALUES ('Mending', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Mending', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Prismatic Spray', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Prismatic Spray', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Mage Armor', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Mage Armor', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Geas', 'Bard');
INSERT INTO classes (name, class) VALUES ('Geas', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Geas', 'Druid');
INSERT INTO classes (name, class) VALUES ('Geas', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Geas', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Conjure Woodland Beings', 'Druid');
INSERT INTO classes (name, class) VALUES ('Conjure Woodland Beings', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Alter Self', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Alter Self', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Haste', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Haste', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Continual Flame', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Continual Flame', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Control Water', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Control Water', 'Druid');
INSERT INTO classes (name, class) VALUES ('Control Water', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Alarm (Ritual)', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Alarm (Ritual)', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Hunter’s Mark', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Illusory Script (Ritual)', 'Bard');
INSERT INTO classes (name, class) VALUES ('Illusory Script (Ritual)', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Illusory Script (Ritual)', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Animal Shapes', 'Druid');
INSERT INTO classes (name, class) VALUES ('Delayed Blast Fireball', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Delayed Blast Fireball', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Dream', 'Bard');
INSERT INTO classes (name, class) VALUES ('Dream', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Dream', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Conjure Barrage', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Chromatic Orb', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Chromatic Orb', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Silent Image', 'Bard');
INSERT INTO classes (name, class) VALUES ('Silent Image', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Silent Image', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Leomund’s Secret Chest', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Cloud of Daggers', 'Bard');
INSERT INTO classes (name, class) VALUES ('Cloud of Daggers', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Cloud of Daggers', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Cloud of Daggers', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Dominate Monster', 'Bard');
INSERT INTO classes (name, class) VALUES ('Dominate Monster', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Dominate Monster', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Dominate Monster', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Sequester', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Compelled Duel', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Locate Object', 'Bard');
INSERT INTO classes (name, class) VALUES ('Locate Object', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Locate Object', 'Druid');
INSERT INTO classes (name, class) VALUES ('Locate Object', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Locate Object', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Locate Object', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Otiluke’s Resilient Sphere', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Heat Metal', 'Bard');
INSERT INTO classes (name, class) VALUES ('Heat Metal', 'Druid');
INSERT INTO classes (name, class) VALUES ('Animal Messenger (Ritual)', 'Bard');
INSERT INTO classes (name, class) VALUES ('Animal Messenger (Ritual)', 'Druid');
INSERT INTO classes (name, class) VALUES ('Animal Messenger (Ritual)', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Eyebite', 'Bard');
INSERT INTO classes (name, class) VALUES ('Eyebite', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Eyebite', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Eyebite', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Magic Circle', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Magic Circle', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Magic Circle', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Magic Circle', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Shield of Faith', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Shield of Faith', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Phantasmal Force', 'Bard');
INSERT INTO classes (name, class) VALUES ('Phantasmal Force', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Phantasmal Force', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Earthbind', 'Druid');
INSERT INTO classes (name, class) VALUES ('Earthbind', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Earthbind', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Earthbind', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Reverse Gravity', 'Druid');
INSERT INTO classes (name, class) VALUES ('Reverse Gravity', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Reverse Gravity', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Wall of Thorns', 'Druid');
INSERT INTO classes (name, class) VALUES ('Glibness', 'Bard');
INSERT INTO classes (name, class) VALUES ('Glibness', 'Warlock');
INSERT INTO classes (name, class) VALUES ('See invisibility', 'Bard');
INSERT INTO classes (name, class) VALUES ('See invisibility', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('See invisibility', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Eldritch Blast', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Raise Dead', 'Bard');
INSERT INTO classes (name, class) VALUES ('Raise Dead', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Raise Dead', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Telepathy', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Flame Arrows', 'Druid');
INSERT INTO classes (name, class) VALUES ('Flame Arrows', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Flame Arrows', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Flame Arrows', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Investiture of Stone', 'Druid');
INSERT INTO classes (name, class) VALUES ('Investiture of Stone', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Investiture of Stone', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Investiture of Stone', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Chill Touch', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Chill Touch', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Chill Touch', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Aid', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Aid', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Mass Suggestion', 'Bard');
INSERT INTO classes (name, class) VALUES ('Mass Suggestion', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Mass Suggestion', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Mass Suggestion', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Power Word Heal', 'Bard');
INSERT INTO classes (name, class) VALUES ('Fear', 'Bard');
INSERT INTO classes (name, class) VALUES ('Fear', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Fear', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Fear', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Rope Trick', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Blade Barrier', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Antimagic Field', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Antimagic Field', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Crusader’s Mantle', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Wall of Sand', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Moonbeam', 'Druid');
INSERT INTO classes (name, class) VALUES ('Mordenkainen’s Faithful Hound', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Thunderwave', 'Bard');
INSERT INTO classes (name, class) VALUES ('Thunderwave', 'Druid');
INSERT INTO classes (name, class) VALUES ('Thunderwave', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Thunderwave', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Hold Person', 'Bard');
INSERT INTO classes (name, class) VALUES ('Hold Person', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Hold Person', 'Druid');
INSERT INTO classes (name, class) VALUES ('Hold Person', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Hold Person', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Hold Person', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Prayer of Healing', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Dominate Beast', 'Druid');
INSERT INTO classes (name, class) VALUES ('Dominate Beast', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Phantom Steed (Ritual)', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Enthrall', 'Bard');
INSERT INTO classes (name, class) VALUES ('Enthrall', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Meteor Swarm', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Meteor Swarm', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Command', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Command', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Create Undead', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Create Undead', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Create Undead', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Thunderclap', 'Bard');
INSERT INTO classes (name, class) VALUES ('Thunderclap', 'Druid');
INSERT INTO classes (name, class) VALUES ('Thunderclap', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Thunderclap', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Thunderclap', 'Wizard');
INSERT INTO classes (name, class) VALUES ('True Resurrection', 'Cleric');
INSERT INTO classes (name, class) VALUES ('True Resurrection', 'Druid');
INSERT INTO classes (name, class) VALUES ('Mass Healing Word', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Ensnaring Strike', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Clairvoyance', 'Bard');
INSERT INTO classes (name, class) VALUES ('Clairvoyance', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Clairvoyance', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Clairvoyance', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Gust', 'Druid');
INSERT INTO classes (name, class) VALUES ('Gust', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Gust', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Mislead', 'Bard');
INSERT INTO classes (name, class) VALUES ('Mislead', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Animate Dead', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Animate Dead', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Tidal Wave', 'Druid');
INSERT INTO classes (name, class) VALUES ('Tidal Wave', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Holy Aura', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Globe of Invulnerability', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Globe of Invulnerability', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Dancing Lights', 'Bard');
INSERT INTO classes (name, class) VALUES ('Dancing Lights', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Dancing Lights', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Message', 'Bard');
INSERT INTO classes (name, class) VALUES ('Message', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Message', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Ice Storm', 'Druid');
INSERT INTO classes (name, class) VALUES ('Ice Storm', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Ice Storm', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Evard’s Black Tentacles', 'Wizard');
INSERT INTO classes (name, class) VALUES ('True Polymorph', 'Bard');
INSERT INTO classes (name, class) VALUES ('True Polymorph', 'Warlock');
INSERT INTO classes (name, class) VALUES ('True Polymorph', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Stone Shape', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Stone Shape', 'Druid');
INSERT INTO classes (name, class) VALUES ('Stone Shape', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Grease', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Swift Quiver', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Revivify', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Revivify', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Find the Path', 'Bard');
INSERT INTO classes (name, class) VALUES ('Find the Path', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Find the Path', 'Druid');
INSERT INTO classes (name, class) VALUES ('Beacon of Hope', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Fly', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Fly', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Fly', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Fabricate', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Spirit Guardians', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Tree Stride', 'Druid');
INSERT INTO classes (name, class) VALUES ('Tree Stride', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Suggestion', 'Bard');
INSERT INTO classes (name, class) VALUES ('Suggestion', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Suggestion', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Suggestion', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Ray of Enfeeblement', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Ray of Enfeeblement', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Mirage Arcane', 'Bard');
INSERT INTO classes (name, class) VALUES ('Mirage Arcane', 'Druid');
INSERT INTO classes (name, class) VALUES ('Mirage Arcane', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Magic Missile', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Magic Missile', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Hypnotic Pattern', 'Bard');
INSERT INTO classes (name, class) VALUES ('Hypnotic Pattern', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Hypnotic Pattern', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Hypnotic Pattern', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Cloudkill', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Cloudkill', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Immolation', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Immolation', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Rary’s Telepathic Bond (Ritual)', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Leomund’s Tiny Hut (Ritual)', 'Bard');
INSERT INTO classes (name, class) VALUES ('Leomund’s Tiny Hut (Ritual)', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Lesser Restoration', 'Bard');
INSERT INTO classes (name, class) VALUES ('Lesser Restoration', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Lesser Restoration', 'Druid');
INSERT INTO classes (name, class) VALUES ('Lesser Restoration', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Lesser Restoration', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Cordon of Arrows', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Feign Death (Ritual)', 'Bard');
INSERT INTO classes (name, class) VALUES ('Feign Death (Ritual)', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Feign Death (Ritual)', 'Druid');
INSERT INTO classes (name, class) VALUES ('Feign Death (Ritual)', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Destructive Wave', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Shocking Grasp', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Shocking Grasp', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Bones of the Earth', 'Druid');
INSERT INTO classes (name, class) VALUES ('Animal Friendship', 'Bard');
INSERT INTO classes (name, class) VALUES ('Animal Friendship', 'Druid');
INSERT INTO classes (name, class) VALUES ('Animal Friendship', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Bigby’s Hand', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Sunburst', 'Druid');
INSERT INTO classes (name, class) VALUES ('Sunburst', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Sunburst', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Abi-Dalzim’s Horrid Wilting', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Abi-Dalzim’s Horrid Wilting', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Nystul’s Magic Aura', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Animate Objects', 'Bard');
INSERT INTO classes (name, class) VALUES ('Animate Objects', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Animate Objects', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Locate Creature', 'Bard');
INSERT INTO classes (name, class) VALUES ('Locate Creature', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Locate Creature', 'Druid');
INSERT INTO classes (name, class) VALUES ('Locate Creature', 'Paladin');
INSERT INTO classes (name, class) VALUES ('Locate Creature', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Locate Creature', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Grasping Vine', 'Druid');
INSERT INTO classes (name, class) VALUES ('Grasping Vine', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Teleportation Circle', 'Bard');
INSERT INTO classes (name, class) VALUES ('Teleportation Circle', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Teleportation Circle', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Burning Hands', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Burning Hands', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Inflict Wounds', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Erupting Earth', 'Druid');
INSERT INTO classes (name, class) VALUES ('Erupting Earth', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Erupting Earth', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Feeblemind', 'Bard');
INSERT INTO classes (name, class) VALUES ('Feeblemind', 'Druid');
INSERT INTO classes (name, class) VALUES ('Feeblemind', 'Warlock');
INSERT INTO classes (name, class) VALUES ('Feeblemind', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Sleep', 'Bard');
INSERT INTO classes (name, class) VALUES ('Sleep', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Sleep', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Silence (Ritual)', 'Bard');
INSERT INTO classes (name, class) VALUES ('Silence (Ritual)', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Silence (Ritual)', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Speak with Dead', 'Bard');
INSERT INTO classes (name, class) VALUES ('Speak with Dead', 'Cleric');
INSERT INTO classes (name, class) VALUES ('Guards and Wards', 'Bard');
INSERT INTO classes (name, class) VALUES ('Guards and Wards', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Levitate', 'Sorcerer');
INSERT INTO classes (name, class) VALUES ('Levitate', 'Wizard');
INSERT INTO classes (name, class) VALUES ('Absorb Elements', 'Druid');
INSERT INTO classes (name, class) VALUES ('Absorb Elements', 'Ranger');
INSERT INTO classes (name, class) VALUES ('Absorb Elements', 'Wizard');
